<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.sporniket.javabeans</groupId>
		<artifactId>sporniket-javabeans</artifactId>
		<version>23.07.01-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>sporniket-javabeans-doclet2</artifactId>
	<packaging>jar</packaging>

	<properties>
		<!-- Using my own tool -->
		<version.sporniket-javabeans-doclet>19.04.00</version.sporniket-javabeans-doclet>
		<!-- maven plugins version -->
		<version.maven-javadoc-plugin>3.0.1</version.maven-javadoc-plugin>
	</properties>

	<name>sporniket-javabeans-doclet2</name>
	<description>Doclet for generating javabeans from a POJO structure.</description>
	<url>${url.base}/blob/master/${project.artifactId}</url>

	<distributionManagement>
		<site>
			<id>localMvnSite-${project.artifactId}</id>
			<name>Sporniket Javabeans Generator - ${project.name}</name>
			<url>${url.base.site.deploy}/${project.parent.artifactId}/module/${project.artifactId}/${project.version}</url>
		</site>
	</distributionManagement>
	<dependencies>
		<!-- ===INTERNAL DEPENDENCIES=== -->
		<dependency>
			<groupId>com.sporniket.javabeans</groupId>
			<artifactId>sporniket-javabeans-models</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.sporniket.javabeans</groupId>
			<artifactId>sporniket-javabeans-models-consumers-javasource</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.sporniket.javabeans</groupId>
			<artifactId>sporniket-javabeans-models-producers-javadoc</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- ===EXTERNAL DEPENDENCIES (non test)=== -->
		<!-- Sporniket core -->
		<dependency>
			<groupId>com.sporniket.core</groupId>
			<artifactId>sporniket-core-io</artifactId>
		</dependency>


		<!-- ===TEST DEPENDENCIES=== -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- bdd assertions -->
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- json orm -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>${version.dependency.jackson}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>${version.dependency.jackson}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
		</plugins>
	</build>
</project>
